### ISSUE TITLE
python-loader repository name

### ISSUE THREAD

**Issue by elmbeech** [PhysiCell-Tools/python-loader#7]
Could the repository be renamed to pyMCDS?

1. this is what pyMCDS_timeseries.py expect at line 4: from pyMCDS import pyMCDS
2. the dash in python-loader will anyway give troubles: 
    from  python-loader import pyMCDS troughs SyntaxError: invalid syntax
   so, with this current setting,  everyone has to rename the package anyway.
3. python-loader is in my opinion not so an informative python library name anyway.

Please consider, thank you, Elmar

**Comment by elmbeech** [comment]
Never mind! The whole repository is packed in a way that you anyway have to set your PYTHONPATH into the repository.

**Comment by elmbeech** [comment]
Never mind. I have not found a way to just clone this package and use it.
The way it is packed there is always some "hacking". YMMW

**Comment by elmbeech** [comment]
I made the necessary changes and generated a pull request.
Please rename the package to physicell_pyloader (or what ever you like, but without dash!).
the import commands for the two classes becomes then as easy as: 
```
from physicell_pyloader import pyMCDS, pyMCDS_timeseries
```

**Comment by MathCancer** [comment]
Is the naming an issue or merely a preference? 

I can't say I've ever had trouble loading this in a python code or Jupyter notebook. (And note that the individual filenames do not have hyphens.) 

Renaming a project or repository that is already deployed and in general use is almost always a bad idea. Backwards compatibility and continuity are important. 

Being "pythonic" is not a good enough reason to break other people's codes and workflows. Do you have a technical reason? Thanks!

**Comment by elmbeech** [comment]
if I clone this repo:
```bash
git clone https://github.com/PhysiCell-Tools/python-loader.git
```
then open a python shell and write:
```python
from python-loader import pyMCDS
```
I will get:
```
In [1]: from python-loader import pyMCDS
  Input In [1]
    from python-loader import pyMCDS
               ^
SyntaxError: invalid syntax
```

so i have to do:
```bash
cd python-loader/
```

then for the loading pyMCDS function i have to write:
```python
from pyMCDS import pyMCDS
```
and for the pyMCDS_timeseries:
```python
from pyMCDS_timeseries import pyMCDS_timeseries
```
and for read_MultiCellDS_xml:
```python
from read_MultiCellDS_xml import read_MultiCellDS_xml
```
so it is *kind of a python package with many names*. 
frankly, i don't know any other python package that you have to load functions in such a way.

natural would for example be something like:
```
from physicell_pyloader import pyMCDS, pyMCDS_timeseries, read_MultiCellDS_xml
```
and it would be possible if there is no dash.

i understand that backwards compatibility is important. 
on the other hand, for people familiar to python who come new to the project,  this will always be an unnecessary hiccup.

another solution would be to turn the package in a proper pip installable python package, as done here: 
+ https://github.com/elmbeech/python-loader
please notice, in this case the *reponame* can stay python-loader because the *python package name* is the folder inside the repo (physicellloader in this case).

All in all, it was just a suggestion.
If it is preferred to leave all as it is, fine with me.

**Comment by elmbeech** [comment]
this issue was resolved with forking pcdl physicell data loader back into python-loader.
